# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alphaType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61lphaType.proto\x12\x07rv.data*Z\n\tAlphaType\x12\x16\n\x12\x41LPHA_TYPE_UNKNOWN\x10\x00\x12\x17\n\x13\x41LPHA_TYPE_STRAIGHT\x10\x01\x12\x1c\n\x18\x41LPHA_TYPE_PREMULTIPLIED\x10\x02\x42\x34\xf8\x01\x01\xaa\x02$Pro.SerializationInterop.RVProtoData\xba\x02\x07RVData_b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alphaType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001\252\002$Pro.SerializationInterop.RVProtoData\272\002\007RVData_'
  _ALPHATYPE._serialized_start=28
  _ALPHATYPE._serialized_end=118
# @@protoc_insertion_point(module_scope)
