# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyticsApi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61nalyticsApi.proto\x12\x0crv.analytics\"b\n\x03\x41PI\x12=\n\x10message_received\x18\x01 \x01(\x0b\x32!.rv.analytics.API.MessageReceivedH\x00\x1a\x11\n\x0fMessageReceivedB\t\n\x07\x41PITypeBA\xf8\x01\x01\xaa\x02.Pro.SerializationInterop.RVProtoData.Analytics\xba\x02\nAnalytics_b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsApi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001\252\002.Pro.SerializationInterop.RVProtoData.Analytics\272\002\nAnalytics_'
  _API._serialized_start=36
  _API._serialized_end=134
  _API_MESSAGERECEIVED._serialized_start=106
  _API_MESSAGERECEIVED._serialized_end=123
# @@protoc_insertion_point(module_scope)
