# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyticsWHMStore.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61nalyticsWHMStore.proto\x12\x0crv.analytics\"\x99\x01\n\x08WHMStore\x12\x36\n\nview_store\x18\x01 \x01(\x0b\x32 .rv.analytics.WHMStore.ViewStoreH\x00\x12\x33\n\x08\x64ownload\x18\x02 \x01(\x0b\x32\x1f.rv.analytics.WHMStore.DownloadH\x00\x1a\x0b\n\tViewStore\x1a\n\n\x08\x44ownloadB\x07\n\x05\x45ventBA\xf8\x01\x01\xaa\x02.Pro.SerializationInterop.RVProtoData.Analytics\xba\x02\nAnalytics_b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsWHMStore_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001\252\002.Pro.SerializationInterop.RVProtoData.Analytics\272\002\nAnalytics_'
  _WHMSTORE._serialized_start=42
  _WHMSTORE._serialized_end=195
  _WHMSTORE_VIEWSTORE._serialized_start=163
  _WHMSTORE_VIEWSTORE._serialized_end=174
  _WHMSTORE_DOWNLOAD._serialized_start=176
  _WHMSTORE_DOWNLOAD._serialized_end=186
# @@protoc_insertion_point(module_scope)
