# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyticsMultiTracks.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61nalyticsMultiTracks.proto\x12\x0crv.analytics\"\x8b\x03\n\x0bMultiTracks\x1a\xd4\x01\n\x07\x41\x63\x63ount\x12;\n\tchart_pro\x18\x01 \x01(\x0e\x32(.rv.analytics.MultiTracks.Account.Status\x12\x44\n\x12propresenter_addon\x18\x02 \x01(\x0e\x32(.rv.analytics.MultiTracks.Account.Status\"F\n\x06Status\x12\x13\n\x0fSTATUS_DISABLED\x10\x00\x12\x14\n\x10STATUS_CANCELLED\x10\x01\x12\x11\n\rSTATUS_ACTIVE\x10\x02\x1a=\n\x07Startup\x12\x32\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32!.rv.analytics.MultiTracks.Account\x1a\x66\n\x06Import\x12\x32\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32!.rv.analytics.MultiTracks.Account\x12\x19\n\x11\x63harts_automation\x18\x02 \x01(\x08\x12\r\n\x05lines\x18\x03 \x01(\x05\x42\x41\xf8\x01\x01\xaa\x02.Pro.SerializationInterop.RVProtoData.Analytics\xba\x02\nAnalytics_b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsMultiTracks_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001\252\002.Pro.SerializationInterop.RVProtoData.Analytics\272\002\nAnalytics_'
  _MULTITRACKS._serialized_start=45
  _MULTITRACKS._serialized_end=440
  _MULTITRACKS_ACCOUNT._serialized_start=61
  _MULTITRACKS_ACCOUNT._serialized_end=273
  _MULTITRACKS_ACCOUNT_STATUS._serialized_start=203
  _MULTITRACKS_ACCOUNT_STATUS._serialized_end=273
  _MULTITRACKS_STARTUP._serialized_start=275
  _MULTITRACKS_STARTUP._serialized_end=336
  _MULTITRACKS_IMPORT._serialized_start=338
  _MULTITRACKS_IMPORT._serialized_end=440
# @@protoc_insertion_point(module_scope)
